# Generated by Django 5.1.7 on 2025-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images/'),
        ),
    ]
