# Generated by Django 5.1.7 on 2025-03-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
